#!/usr/bin/env bash
set -euox pipefail

function repo_root() {
  git rev-parse --show-toplevel
}

function project_version() {
  # VERSION derived from CHANGELOG and automated release library
  fullVersion=$(<"$(repo_root)/VERSION")
  # Only use base version (strip any suffix, e.g. "-dev" or build number)
  if [[ "$fullVersion" == *-* ]]; then
    echo "${fullVersion%%-*}"
  else
    echo "$fullVersion"
  fi
}

# Create a clean copy of the source code for build
cp -a /src /build
git config --global --add safe.directory /build
cd /build
git clean -fdx || :
# Copy the VERSION file generated by the CI to the build directory
cp /src/VERSION /build/VERSION

# Restore nuget packages
dotnet restore

# test
dotnet build
dotnet test --logger:"junit;LogFileName=/build/TestResults.xml"
dotnet test --collect:"Code Coverage;Format=Cobertura" --results-directory:"/build/TestResults"
cp /build/TestResults/*/*.cobertura.xml /build/Coverage.xml

# build
VERSION=$(project_version)
#TODO: Use base version only
dotnet build api-dotnet.sln --configuration Release /p:AssemblyVersion="$VERSION"

# package
mkdir nugetPackages
dotnet pack -o ./nugetPackages --version-suffix "$VERSION"
